In [54]:
import numpy
import pandas
import os
import sys
sys.path.append(os.path.abspath('../../'))
from epiweeks import Week

# COVID_5 Dashboard

#### Case Counts

In [55]:
weekly_data_counts = pandas.read_csv(os.path.join('COVID19_5', 'Weekly_Data_Counts.csv'), skiprows=2)
weekly_data_counts.dropna(inplace=True)
weekly_data_counts['MMWR-YEAR'] = weekly_data_counts['WEEK_NUMBER'].apply(lambda x: x.split('-')[0])
weekly_data_counts['MMWR-WEEK'] = weekly_data_counts['WEEK_NUMBER'].apply(lambda x: x.split('-')[1])
weekly_data_counts['MMWR-DATE'] = weekly_data_counts.apply(lambda x: str(Week.fromstring(f"{x['MMWR-YEAR']}" + f"{int(x['MMWR-WEEK']):02d}").enddate()), axis=1)

In [56]:
weekly_data_counts.head()

,YEAR,WEEK_NUMBER,0-4 YR,5-17 YR,18-49 YR,50-64 YR,65+ YR,MMWR-YEAR,MMWR-WEEK,MMWR-DATE
0,2020-21,2020-10,0.0,0.0,10.0,7.0,17.0,2020,10,2020-03-07
1,2020-21,2020-11,0.0,0.0,50.0,79.0,83.0,2020,11,2020-03-14
2,2020-21,2020-12,0.0,3.0,253.0,286.0,413.0,2020,12,2020-03-21
3,2020-21,2020-13,6.0,5.0,636.0,793.0,1060.0,2020,13,2020-03-28
4,2020-21,2020-14,11.0,11.0,656.0,1024.0,1404.0,2020,14,2020-04-04

#### Case Percentages

In [57]:
weekly_data_percents = pandas.read_csv(os.path.join('COVID19_5', 'Weekly_Data_Percent.csv'), skiprows=2)
weekly_data_percents.dropna(inplace=True)
weekly_data_percents['MMWR-YEAR'] = weekly_data_percents['WEEK_NUMBER'].apply(lambda x: x.split('-')[0])
weekly_data_percents['MMWR-WEEK'] = weekly_data_percents['WEEK_NUMBER'].apply(lambda x: x.split('-')[1])
weekly_data_percents['MMWR-DATE'] = weekly_data_percents.apply(lambda x: str(Week.fromstring(f"{x['MMWR-YEAR']}" + f"{int(x['MMWR-WEEK']):02d}").enddate()), axis=1)

In [58]:
weekly_data_percents.head()

,YEAR,WEEK_NUMBER,0-4 YR,5-17 YR,18-49 YR,50-64 YR,65+ YR,MMWR-YEAR,MMWR-WEEK,MMWR-DATE
0,2020-21,2020-10,0.0,0.0,29.4,20.6,50.0,2020,10,2020-03-07
1,2020-21,2020-11,0.0,0.0,23.6,37.3,39.2,2020,11,2020-03-14
2,2020-21,2020-12,0.0,0.3,26.5,29.9,43.2,2020,12,2020-03-21
3,2020-21,2020-13,0.2,0.2,25.4,31.7,42.4,2020,13,2020-03-28
4,2020-21,2020-14,0.4,0.4,21.1,33.0,45.2,2020,14,2020-04-04

# COVID_3 Dashboard

####

In [59]:
all_data = pandas.read_csv(os.path.join('COVID19_3', 'COVID-19Surveillance_All_Data.csv'), skiprows=2)
all_data.dropna(inplace=True)
all_data['MMWR-DATE'] = all_data.apply(lambda x: str(Week.fromstring(f"{int(x['MMWR-YEAR'])}" + f"{int(x['MMWR-WEEK']):02d}").enddate()), axis=1)

In [60]:
all_data

,CATCHMENT,NETWORK,YEAR,MMWR-YEAR,MMWR-WEEK,AGE CATEGORY,SEX,RACE,CUMULATIVE RATE,WEEKLY RATE,MMWR-DATE
0,Entire Network,EIP,2020-21,2020.0,10.0,Overall,Overall,Overall,0.1,0.1,2020-03-07
1,Georgia,EIP,2020-21,2020.0,10.0,Overall,Overall,White,0.2,0.2,2020-03-07
2,Minnesota,EIP,2020-21,2020.0,10.0,Overall,Overall,Black,0.0,0.0,2020-03-07
3,Minnesota,EIP,2020-21,2020.0,10.0,Overall,Overall,Hispanic/Latino,0.0,0.0,2020-03-07
4,Minnesota,EIP,2020-21,2020.0,10.0,Overall,Overall,Asian/Pacific Islander,0.0,0.0,2020-03-07
...,...,...,...,...,...,...,...,...,...,...,...
57030,Minnesota,EIP,2020-21,2022.0,3.0,>= 18,Overall,Overall,1197.5,16.2,2022-01-22
57031,Michigan,IHSP,2020-21,2022.0,3.0,>= 18,Overall,Overall,1216.0,21.5,2022-01-22
57032,Maryland,EIP,2020-21,2022.0,3.0,>= 18,Overall,Overall,1068.9,0.0,2022-01-22
57033,California,EIP,2020-21,2022.0,3.0,>= 18,Overall,Overall,732.3,22.5,2022-01-22
57034,Entire Network,IHSP,2020-21,2022.0,3.0,>= 18,Overall,Overall,813.7,6.9,2022-01-22

__Remark__: According to the CDC Dashboard (COVID19_3), the values above seem to be rates per 100,000 populations.